In [1]:
from __future__ import print_function
import os, sys
sys.path.append('./gcn')

import torch
import torch.nn as nn
from torch.nn import Parameter
import torch.nn.functional as F
import torch.optim as optim
from preprocess import*
from torchdata import*
from loss import*
from network import*
from gcn.models import GCN
import numpy as np
import pandas as pd
import random

In [2]:
solver = Solver( z_dim=32, encodeLayer=[256,64], decodeLayer=[64,256], nfeat=32, nclasses=6, 
                sigma=1/np.exp(4.5), entropy_thr=10, Lambda_global=200, Lambda_local=0.001, 
                beta=0.65, alpha=1.0, use_target=1, unas_thr=1.5, use_filter=False, filter_index=False,
                ndomain=3, batch_size=256, highly_variable=2000, learning_rate=0.002)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 5  6  8  9 11 12]
[ 5  6  7  8  9 11 12]
[ 2  5  6  7  8  9 10 11 12]
[ 5  6  7 12]
Dataset loaded!
Model initialized!
Statistics initialized!
Optimizer defined!


In [3]:
for t in range(200):
    num = solver.train_gcn_adapt(t)
    best_acc = solver.test(t)

Train Epoch:   0 [  1/1.3984375 (0.72%)]	Loss_zinb: 1.92483	Loss_cls_domain: 1.79981	Loss_cls_source: 1.74309	Loss_cls_target: 0.29537	Loss_global: 142.60490	Loss_local: 0.00000

Test set: Average loss: 0.0000, Accuracy: 1017/2282 (44.5662%), Best Accuracy: 1017/2282 (44.5662%)  

Train Epoch:   1 [  1/1.3984375 (0.72%)]	Loss_zinb: 1.88081	Loss_cls_domain: 1.91463	Loss_cls_source: 1.64241	Loss_cls_target: 0.29475	Loss_global: 255.06796	Loss_local: 0.00000

Test set: Average loss: 0.0000, Accuracy: 1119/2282 (49.0359%), Best Accuracy: 1119/2282 (49.0359%)  

Train Epoch:   2 [  1/1.3984375 (0.72%)]	Loss_zinb: 1.87292	Loss_cls_domain: 1.77878	Loss_cls_source: 1.50904	Loss_cls_target: 0.29312	Loss_global: 266.20587	Loss_local: 0.00000


Exception ignored in: <function _releaseLock at 0x7ff7efbf89e0>
Traceback (most recent call last):
  File "/data/msyuan/anaconda3/lib/python3.7/logging/__init__.py", line 221, in _releaseLock
    def _releaseLock():
KeyboardInterrupt: 


RuntimeError: DataLoader worker (pid(s) 36347) exited unexpectedly

In [3]:
for t in range(10):
    print('Pre train Epoch: ', t)
    num = solver.train_gcn_baseline(t)
    best_acc = solver.test(t)
index = solver.open_filter()

Pre train Epoch:  0
Train Epoch:   0 [  1/8.2890625 (0.12%)]	Loss_zinb: 0.33845	Loss_cls_domain: 2.24155	Loss_cls_source: 2.13571	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   0 [  3/8.2890625 (0.36%)]	Loss_zinb: 0.32878	Loss_cls_domain: 2.04141	Loss_cls_source: 1.82368	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   0 [  5/8.2890625 (0.60%)]	Loss_zinb: 0.34077	Loss_cls_domain: 1.77141	Loss_cls_source: 1.23221	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   0 [  7/8.2890625 (0.84%)]	Loss_zinb: 0.32649	Loss_cls_domain: 1.41663	Loss_cls_source: 0.80245	Loss_global: nan	Loss_local: 0.00001
Train Epoch:   0 [  9/8.2890625 (1.09%)]	Loss_zinb: 0.27687	Loss_cls_domain: 1.11877	Loss_cls_source: 0.48988	Loss_global: nan	Loss_local: 0.00001
Train Epoch:   0 [ 11/8.2890625 (1.33%)]	Loss_zinb: 0.23561	Loss_cls_domain: 1.40439	Loss_cls_source: 0.48313	Loss_global: nan	Loss_local: 0.00001
Train Epoch:   0 [ 13/8.2890625 (1.57%)]	Loss_zinb: 0.19727	Loss_cls_domain: 1.03369	Loss_cls_sour

Train Epoch:   4 [ 11/8.2890625 (1.33%)]	Loss_zinb: 0.15068	Loss_cls_domain: 0.33734	Loss_cls_source: 0.05608	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   4 [ 13/8.2890625 (1.57%)]	Loss_zinb: 0.14785	Loss_cls_domain: 0.16144	Loss_cls_source: 0.06124	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   4 [ 15/8.2890625 (1.81%)]	Loss_zinb: 0.14353	Loss_cls_domain: 0.21384	Loss_cls_source: 0.04178	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   4 [ 17/8.2890625 (2.05%)]	Loss_zinb: 0.15082	Loss_cls_domain: 0.16797	Loss_cls_source: 0.03640	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   4 [ 19/8.2890625 (2.29%)]	Loss_zinb: 0.14464	Loss_cls_domain: 0.18552	Loss_cls_source: 0.03503	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   4 [ 21/8.2890625 (2.53%)]	Loss_zinb: 0.14562	Loss_cls_domain: 0.15523	Loss_cls_source: 0.05394	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   4 [ 23/8.2890625 (2.77%)]	Loss_zinb: 0.14551	Loss_cls_domain: 0.16599	Loss_cls_source: 0.03358	Loss_glo


Test set: Average loss: 0.0000, Accuracy: 954/2122 (44.9576%), Best Accuracy: 1444/2122 (68.0490%)  

Pre train Epoch:  9
Train Epoch:   9 [  1/8.2890625 (0.12%)]	Loss_zinb: 0.14567	Loss_cls_domain: 0.10590	Loss_cls_source: 0.02829	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   9 [  3/8.2890625 (0.36%)]	Loss_zinb: 0.13253	Loss_cls_domain: 0.08370	Loss_cls_source: 0.02189	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   9 [  5/8.2890625 (0.60%)]	Loss_zinb: 0.14992	Loss_cls_domain: 0.10341	Loss_cls_source: 0.02324	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   9 [  7/8.2890625 (0.84%)]	Loss_zinb: 0.15067	Loss_cls_domain: 0.09602	Loss_cls_source: 0.02340	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   9 [  9/8.2890625 (1.09%)]	Loss_zinb: 0.15492	Loss_cls_domain: 0.10619	Loss_cls_source: 0.05978	Loss_global: nan	Loss_local: 0.00000
Train Epoch:   9 [ 11/8.2890625 (1.33%)]	Loss_zinb: 0.14291	Loss_cls_domain: 0.16393	Loss_cls_source: 0.02744	Loss_global: nan	Loss_local: 0.0

In [4]:
X_all, label_all = prepro("Baron_human+Muraro")
X1, label1 = prepro("Baron_human")
X2, label2 = prepro("Muraro")
len_1,len_2 = len(label1),len(label2) 
label1 = label_all[:-len_2]
label2 = label_all[-len_2:]
print(len(index))
print(np.sum([label2==[12]]))
print(np.sum([label2[index]==[12]]))

1504
448
127


In [5]:
solver = Solver( z_dim=32, encodeLayer=[256,64], decodeLayer=[64,256], nfeat=32, nclasses=8, 
                sigma=1/np.exp(4.5), entropy_thr=10, Lambda_global=20, Lambda_local=0.001, 
                beta=0.65, alpha=1.0, use_target=1, unas_thr=3e-2, use_filter=True, filter_index=index,
                ndomain=2, batch_size=256, highly_variable=2000, learning_rate=0.002)

[   1    2    4 ... 2119 2120 2121]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 2  5  6  7  8  9 10 11 12]
8066
8066
Filtered dataset loaded!
Model initialized!
Statistics initialized!
Optimizer defined!


In [6]:
for t in range(100):
    print('Epoch: ', t)
    num = solver.train_gcn_adapt(t)
    bestacc = solver.test(t)

Epoch:  0
Train Epoch:   0 [  1/7.80859375 (0.13%)]	Loss_zinb: 1.10631	Loss_cls_domain: 2.09772	Loss_cls_source: 2.06230	Loss_cls_target: 0.25766	Loss_global: 16.99969	Loss_local: 0.00000
Train Epoch:   0 [  3/7.80859375 (0.38%)]	Loss_zinb: 1.12130	Loss_cls_domain: 2.02687	Loss_cls_source: 1.70743	Loss_cls_target: 0.25632	Loss_global: 26.66663	Loss_local: 0.00000
Train Epoch:   0 [  5/7.80859375 (0.64%)]	Loss_zinb: 1.04514	Loss_cls_domain: 1.91613	Loss_cls_source: 1.30248	Loss_cls_target: 0.24748	Loss_global: 26.66808	Loss_local: 0.00000

Test set: Average loss: 0.0000, Accuracy: 1236/2272 (54.4014%), Best Accuracy: 1236/2272 (54.4014%)  

Epoch:  1
Train Epoch:   1 [  1/7.80859375 (0.13%)]	Loss_zinb: 1.02510	Loss_cls_domain: 1.84778	Loss_cls_source: 1.20843	Loss_cls_target: 0.23241	Loss_global: 26.66708	Loss_local: 0.00000
Train Epoch:   1 [  3/7.80859375 (0.38%)]	Loss_zinb: 0.86247	Loss_cls_domain: 1.73583	Loss_cls_source: 1.02623	Loss_cls_target: 0.19672	Loss_global: 26.68793	Loss_l


Test set: Average loss: 0.0000, Accuracy: 1445/2272 (63.6004%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  13
Train Epoch:  13 [  1/7.80859375 (0.13%)]	Loss_zinb: 0.52324	Loss_cls_domain: 1.30916	Loss_cls_source: 0.18297	Loss_cls_target: 0.04370	Loss_global: 25.35595	Loss_local: 0.00007
Train Epoch:  13 [  3/7.80859375 (0.38%)]	Loss_zinb: 0.52681	Loss_cls_domain: 0.72489	Loss_cls_source: 0.23645	Loss_cls_target: 0.04263	Loss_global: 31.30785	Loss_local: 0.00005
Train Epoch:  13 [  5/7.80859375 (0.64%)]	Loss_zinb: 0.53042	Loss_cls_domain: 0.79789	Loss_cls_source: 0.24377	Loss_cls_target: 0.03640	Loss_global: 32.37571	Loss_local: 0.00007

Test set: Average loss: 0.0000, Accuracy: 1456/2272 (64.0845%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  14
Train Epoch:  14 [  1/7.80859375 (0.13%)]	Loss_zinb: 0.52597	Loss_cls_domain: 1.66443	Loss_cls_source: 0.15876	Loss_cls_target: 0.03515	Loss_global: 39.27097	Loss_local: 0.00015
Train Epoch:  14 [  3/7.80859375 (0.38%)]	Loss_zinb: 0.518


Test set: Average loss: 0.0000, Accuracy: 1252/2272 (55.1056%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  26
Train Epoch:  26 [  1/7.80859375 (0.13%)]	Loss_zinb: 0.52248	Loss_cls_domain: 0.48601	Loss_cls_source: 0.16897	Loss_cls_target: 0.03402	Loss_global: 213.81027	Loss_local: 0.00020
Train Epoch:  26 [  3/7.80859375 (0.38%)]	Loss_zinb: 0.49800	Loss_cls_domain: 4.23266	Loss_cls_source: 0.34660	Loss_cls_target: 0.03562	Loss_global: 237.95834	Loss_local: 0.00030
Train Epoch:  26 [  5/7.80859375 (0.64%)]	Loss_zinb: 0.50957	Loss_cls_domain: 12.77124	Loss_cls_source: 0.21157	Loss_cls_target: 0.03276	Loss_global: 391.33337	Loss_local: 0.00022

Test set: Average loss: 0.0000, Accuracy: 1272/2272 (55.9859%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  27
Train Epoch:  27 [  1/7.80859375 (0.13%)]	Loss_zinb: 0.50510	Loss_cls_domain: 18.47084	Loss_cls_source: 0.37086	Loss_cls_target: 0.02963	Loss_global: 65.03165	Loss_local: 0.00013
Train Epoch:  27 [  3/7.80859375 (0.38%)]	Loss_zinb: 


Test set: Average loss: 0.0000, Accuracy: 906/2272 (39.8768%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  41

Test set: Average loss: 0.0000, Accuracy: 896/2272 (39.4366%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  42

Test set: Average loss: 0.0000, Accuracy: 916/2272 (40.3169%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  43

Test set: Average loss: 0.0000, Accuracy: 903/2272 (39.7447%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  44
Train Epoch:  44 [  1/7.80859375 (0.13%)]	Loss_zinb: 0.53865	Loss_cls_domain: 32.54168	Loss_cls_source: 0.92785	Loss_cls_target: 0.03679	Loss_global: 30898.53516	Loss_local: 0.00087

Test set: Average loss: 0.0000, Accuracy: 935/2272 (41.1532%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  45
Train Epoch:  45 [  1/7.80859375 (0.13%)]	Loss_zinb: 0.51374	Loss_cls_domain: 25.66884	Loss_cls_source: 0.90824	Loss_cls_target: 0.03036	Loss_global: 196.67778	Loss_local: 0.00035

Test set: Average loss: 0.0000, Accuracy: 262/2272 (11.5317%), Best

Train Epoch:  89 [  1/7.80859375 (0.13%)]	Loss_zinb: 0.51136	Loss_cls_domain: 7.18123	Loss_cls_source: 0.66595	Loss_cls_target: 0.01592	Loss_global: 28465064.00000	Loss_local: 0.00170

Test set: Average loss: 0.0000, Accuracy: 326/2272 (14.3486%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  90

Test set: Average loss: 0.0000, Accuracy: 334/2272 (14.7007%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  91

Test set: Average loss: 0.0000, Accuracy: 327/2272 (14.3926%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  92

Test set: Average loss: 0.0000, Accuracy: 330/2272 (14.5246%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  93

Test set: Average loss: 0.0000, Accuracy: 342/2272 (15.0528%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  94

Test set: Average loss: 0.0000, Accuracy: 337/2272 (14.8327%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  95

Test set: Average loss: 0.0000, Accuracy: 341/2272 (15.0088%), Best Accuracy: 1551/2272 (68.2658%)  

Epoch:  96

Test set: Average

In [13]:
solver.test_feature("/data/msyuan/results/scMSDA/Ablation/use_target_1_ndomain_3/")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 5  6  8  9 11 12]
[ 5  6  7  8  9 11 12]
[ 2  5  6  7  8  9 10 11 12]
[ 5  6  7 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 5  6  8  9 11 12]
[ 5  6  7  8  9 11 12]
[ 2  5  6  7  8  9 10 11 12]
[ 5  6  7 12]


In [5]:
solver.latent_feature("/data/msyuan/results/scMSDA/multi_source_insufficient_b_4/")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 5  6  8  9 11 12]
[ 5  6  7  8  9 11 12]
[ 2  5  6  7  8  9 10 11 12]
[ 5  6  7 12]


In [5]:
pred = pd.DataFrame(bestacc[0])
true = pd.DataFrame(bestacc[1])
pred.to_csv("/data/msyuan/results/scMSDA/multisource_insufficient_scMSDA_pred.csv")
true.to_csv("/data/msyuan/results/scMSDA/multisource_insufficient_scMSDA_true.csv")